[project]
name = "sms_sender"
version = "0.1.0"
description = "SMS Sender App"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "flet>=0.21.0",
    "plyer",
    "flet-permission-handler"
]

[tool.flet]
# Flet Build settings

[tool.flet.android]
permissions = [
    "android.permission.SEND_SMS",
    "android.permission.READ_PHONE_STATE"
]