name: Build Flet APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install flet

      - name: Build APK
        uses: flet-dev/flet-build-action@v1
        with:
          command: flet build apk --module-name sms
          upload-artifact: true